from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


def _locked_package_block(lock: str, package: str) -> str:
    return lock.split(f"{package}==", maxsplit=1)[1].split("\n\n", maxsplit=1)[0]


def test_windows_dependencies_are_pinned_and_hashed() -> None:
    lock = (ROOT / "requirements.lock").read_text(encoding="utf-8")

    assert "autogenerated by uv" in lock
    for package in ("colorama", "cffi"):
        block = _locked_package_block(lock, package)
        assert "win32" in block
        assert "--hash=sha256:" in block


def test_release_bootstrap_keeps_commands_at_repository_root() -> None:
    workflow = (ROOT / ".github/workflows/tauri-release.yml").read_text(encoding="utf-8")

    assert "cd frontend && npm ci" not in workflow
    assert "npm --prefix frontend ci" in workflow
    assert "cargo fetch --locked --manifest-path frontend/src-tauri/Cargo.toml" in workflow
    assert "self-hosted" not in workflow
    assert 'os_runner: "macos-15-intel"' in workflow
    assert 'os_runner: "macos-15"' in workflow
    assert "rustup default 1.88.0" in workflow
    assert workflow.index("Build Python Sidecar (Unix)") < workflow.index("Offline Verifications")
    assert workflow.index("Build Python Sidecar (Windows)") < workflow.index("Offline Verifications")

    windows_sidecar = workflow.split("Build Python Sidecar (Windows)", maxsplit=1)[1].split(
        "Offline Verifications", maxsplit=1
    )[0]
    assert "mkdir -p" not in windows_sidecar
    assert "New-Item -ItemType Directory -Force" in windows_sidecar
    assert "Copy-Item -Force" in windows_sidecar


def test_rust_toolchain_matches_manifest_msrv() -> None:
    toolchain = (ROOT / "rust-toolchain.toml").read_text(encoding="utf-8")
    manifest = (ROOT / "frontend/src-tauri/Cargo.toml").read_text(encoding="utf-8")

    assert 'channel = "1.88.0"' in toolchain
    assert 'rust-version = "1.88.0"' in manifest
